/*DROP TABLE IF EXISTS person;
COMMIT;*/

/*CREATE TABLE person (
	id numeric(19, 0) IDENTITY(1,1) NOT NULL,
	first_name [varchar](255) NULL,
	last_name [varchar](255) NULL,
PRIMARY KEY CLUSTERED
(
	id ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

COMMIT;*/

INSERT INTO person VALUES(1, 'A', 'B');
INSERT INTO person VALUES(2, 'C', 'D');
INSERT INTO person VALUES(3, 'E', 'F');

COMMIT;